version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tasks
    restart: always
    environment:
      POSTGRES_USER: lemotip
      POSTGRES_PASSWORD: wsxmok
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: lemotip
      DB_PASSWORD: wsxmok
      DB_NAME: tasks
    stdin_open: true
    tty: true

volumes:
  db_data:
