services:
  db:
    image: postgres:15-alpine
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: lemotip
      POSTGRES_PASSWORD: wsxmok
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./server
    image: server:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: lemotip
      DB_PASSWORD: wsxmok
      DB_NAME: tasks
      PORT: 8080
      WAIT_HOST: db
      WAIT_PORT: 5432   
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: on-failure
    entrypoint: ["/server/wait-and-run-server.sh"]

  client:
    build: ./client
    image: client:latest
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh"]

volumes:
  db_data:

#cppcheck --enable=all --inconclusive --force --suppress=missingIncludeSystem --output-file=report.txt .